### ISSUE TITLE
settings_server.py is missing

### ISSUE THREAD

**Issue by pipwilson** [xurble/FeedThing#1]
Hello unknown internet person,

`$ python manage.py createsuperuser`

```
File "BLAH/FeedThing/settings.py", line 7, in <module>
import settings_server
ImportError: No module named settings_server
```

In .gitignore we have:

`settings_server.py`

Coincidence?

**Comment by xurble** [comment]
Yeah, should probably. write a readme.  settings_server.py has all the stuff specific to an installation and that you wouldn't want to check into git like `SECRET_KEY` and database details and stuff.

**Comment by xurble** [comment]
I've included an examples settings_server file for reference.
