### ISSUE TITLE
Does Feedthing still under developing or does it accept pull request?

### ISSUE THREAD

**Issue by renpj** [xurble/FeedThing#4]
I've tried FeedThing these days and very like it. Before feedthing, I used google reader and inoreader. However, they are both not possible for me now. I'm looking for a simple app to help me managing RSS feeds. I'm also developing a self-hosted website based on Django. So Feedthing is a good choice for me. I'm wondering does Feedthing still under developing or does it accept pull request? For example, scroll spying is very useful to label the item read/unread state. I will take time to add this feature into feedthing and I'd like to contribute it to this project.

**Comment by xurble** [comment]
Sorry, didn't see this. It wasn't being developed then.  I've just spent a week or so modernizing it a bit. So it is being developed now.
